### ISSUE TITLE
Players in multiplayer cant see what is in each others back slot in 1.20.1 version

### ISSUE THREAD

**Issue by SpottedMarmot** [HollowedWanderer/Combat-Amenities#1]
I cant attach the modpack here since its a .mrpack, but I have Images

My POV:
![image](https://github.com/user-attachments/assets/ab2ac6bc-1bef-466a-8692-922b9035e41f)

Oakie's POV:
![image](https://github.com/user-attachments/assets/949819c5-9d15-4767-a92f-8a7ba769add0)

**Comment by HollowedWanderer** [comment]
oops, did not mean to close. Sorry trying to figure out how to label these things

**Comment by HollowedWanderer** [comment]
fixed in latest update :D
