### ISSUE TITLE
[SUGGESTION] Shield and bow backslots

### ISSUE THREAD

**Issue by Rinku-pup** [HollowedWanderer/Combat-Amenities#16]
When a weapon is on the back slot, it feels wrong to see the shield on the secondary hand so, I propose a backslot for the shield (And for the bow... why? WHY NOT)
![imagen_2024-12-22_201941212](https://github.com/user-attachments/assets/457dd9e4-2d7c-4439-a35a-2f42cb59de34)

**Comment by HollowedWanderer** [comment]
what do you mean by this? It looks normal...?

I'm slightly confused

**Comment by Rinku-pup** [comment]
> what do you mean by this? It looks normal...?
> 
> I'm slightly confused

I mean, it would look better if the shield was in the player's back

**Comment by Helpbot3000** [comment]
> what do you mean by this? It looks normal...?
> 
> I'm slightly confused

I think they are saying they think there should be a way to put the shield on the back with the weapon simultaneously. I feel like that would be tricky to implement smoothly, though.

**Comment by HollowedWanderer** [comment]
So... kind of just a second back slot..?

**Comment by HollowedWanderer** [comment]
I have decided that I don't really want to add another back slot

If someone wants to make an addon to add a second one, feel free, but I feel like it just doesn't fit the base mod and is sort of feature bloat
