### ISSUE TITLE
The backslot item orientation doesn't makes sense (If the player is right handed)

### ISSUE THREAD

**Issue by Rinku-pup** [HollowedWanderer/Combat-Amenities#18]
If you draw a sword as a right hander the handle should be on the back of your right shoulder.

(As it currently looks like):
![32](https://github.com/user-attachments/assets/a00aef89-1ba4-44f7-927e-698dbb4ea3cd)
(How it should look like):
![12](https://github.com/user-attachments/assets/70a56c8c-5c86-43fe-900e-0a9ab65b2f20)

I propose a setting that customizes the sword orientation

**Comment by HollowedWanderer** [comment]
I get how it could be seen as an "issue," but you could theoretically just reach to your other shoulder, and you also don't have to be rude about it

**Comment by Helpbot3000** [comment]
Is there a way that I could alter the model to flip it? It's not a big issue for me but now that this dude pointed it out it's gonna bug me

**Comment by HollowedWanderer** [comment]
I changed it in the WIP update already, but if it is absolutely necessary you can just change the default.json to rotate items 180 degrees with a texture pack

**Comment by HollowedWanderer** [comment]
I actually have decided to actually revert the change in favor of the belt slot.
