### ISSUE TITLE
Enchanting Issues

### ISSUE THREAD

**Issue by thomasroberts3347** [HollowedWanderer/Combat-Amenities#22]
When I attempt to enchant while using combat amenities, I am unable to use the Unbreaking III and Mending books -- see attached image. Have confirmed that, when this mod is removed, enchanting works as normal.

![image](https://github.com/user-attachments/assets/9cd5a87d-dfae-499e-9b35-8a5c8b425df0)
_book in question is Unbreaking III, pick already had Silk Touch, Mending, Eff 4._

Combining tools appears to work as normal, as does enchanting with other books (I tried a prot II book). Enchanting appears to work correctly in creative mode.

Another issue I found:
/enchant username minecraft:loyalty
returns "Trident cannot support that enchantment"

I am using Fabric and have also got Fabric API installed. Other mods I am using:
BetterF3
Sodium

I have edited the config file to set all options except riptideFix to "false".

**Comment by HollowedWanderer** [comment]
Forgot that the enchantments not being dynamically unregistered would cause issues...

Fixed it
