### ISSUE TITLE
When item is switched to back slot, the pick up animation thing does not play

### ISSUE THREAD

**Issue by Helpbot3000** [HollowedWanderer/Combat-Amenities#24]
I really have no idea how to properly title this. I just noticed that the item doesn't do that little stretching animation they do when you pick an item up or switch it to your offhand when switched to the back slot. You can see what I mean by just comparing what happens when you press F versus pressing R

**Comment by HollowedWanderer** [comment]
I didn't think it was really an issue, but I guess I could just mess with the matrices a bit to add a little stretch animation

**Comment by HollowedWanderer** [comment]
I really don't know why I spent an hour fixing this

**Comment by Helpbot3000** [comment]
Yeah sorry it's not really important I just have OCD so I notice these kinds of things
