### ISSUE TITLE
[Feature Request] In-inventory keybind for backslot switching

### ISSUE THREAD

**Issue by TheTrueYak** [HollowedWanderer/Combat-Amenities#4]
When navigating the inventory, the vanilla swap hands keybind (default F) can be used to swap the offhand stack and whatever stack the cursor is hovering over. I think that the backslot also having this feature would be really helpful for quickly navigating the inventory and swapping the current backslot stack. Ideally it would work the same way as the vanilla feature, pressing the backslot swap key would swap the backslot stack and whatever stack the cursor is hovering over, if it is hovering over one.

**Comment by HollowedWanderer** [comment]
done!
