### ISSUE TITLE
Keep item config

### ISSUE THREAD

**Issue by medecoole** [HollowedWanderer/Combat-Amenities#5]
Hello, i was playing with the mod and had an idea, what if you kept the item on death? it might be unbalanced or not liked by some so maybe it could be a gamerule or in a configuration file. i dont know how hard it would be to make, but it would seem pretty nice for modpacks with custom ability items/weapons that you would like to keep after death!

PS: i made a custom trident/hammer mod and the model is slightly angled (i assume to account for the normal trident), but how would i go about adding compatability or fixing it in any way?

**Comment by medecoole** [comment]
![2024-10-17_12 02 20](https://github.com/user-attachments/assets/51e556f8-de1c-4767-9510-9b7a4634f733)
here is the model being wierd

**Comment by HollowedWanderer** [comment]
Neat, I'll probably add that in 2.0.0

Also, currently there is no way to increase compatibility yet sadly. However, in the next major update I plan on adding a way to make datapacks to changes the transforms of any item while on the back slot.  :D

**Comment by TheTrueYak** [comment]
you can technically add compatibility on your own: because the backslot uses the "fixed" item renderer, aka item frames, you can use blockbench to pose how your item looks in item frames and those changes will be reflected in the backslot too.

**Comment by HollowedWanderer** [comment]
Added a gamerule in the WIP update!
