### ISSUE TITLE
Mending items in the backslot do not repair when experience is gained.

### ISSUE THREAD

**Issue by ForestMinecraft** [HollowedWanderer/Combat-Amenities#8]
Items enchanted with mending in the backslot do not repair when experience is gained.

**Comment by HollowedWanderer** [comment]
This is a neat idea actually, I will probably add that in the next update

**Comment by HollowedWanderer** [comment]
I removed durability! (because it sucked anyways) :D

So, I guess this doesn't really apply anymore
