### ISSUE TITLE
HUD backslot overlaps with Axiom's 10th slot

### ISSUE THREAD

**Issue by ScienceMind11** [HollowedWanderer/Combat-Amenities#9]
![image](https://github.com/user-attachments/assets/7751266b-a083-462d-9b87-29238d984036)
Quartz block is in backslot, Axiom's 10th slot is selected, this occurs. Backslot also completely covers the 10th slot when it is not selected.

**Comment by HollowedWanderer** [comment]
Im not entirely sure how to fix this....

**Comment by HollowedWanderer** [comment]
HUD slot position is now configurable in the .properties file!! :D
